### ISSUE TITLE
Spam click on background on kord.app/login creates masive lagg

### ISSUE THREAD

**Issue by sepcol** [bundit/kord-app#47] opened 2021-02-23 09:08 UTC
Navigate to https://www.kord.app/login and spam left mouse click on the background.
The background creates connections to the lines on each click but it has no limit on how many connections it creates.
When spamming massively it creates a huge amount of lagg.

Maybe limit the amount of connections that can be made?

Thanks for your work, I love the application and use it daily!

**Comment by bundit** [comment] 2022-06-10 20:56
Thanks for the suggestion - I don't see much value in limiting the connections and in doing so would be a confusing experience for the user. Closing as "working as intended"

**Closed by bundit** 2022-06-10 20:56 UTC
